movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('', views.start),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.index, name='index'),
    path('search/<str:sort>/', views.search, name="search"),
    path('index/<str:sort>/', views.index, name='index_sort'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'),
    path('<int:movie_pk>/review/create/', views.review_create, name='review_create'),
    path('<int:movie_pk>/review/<int:review_pk>/like/', views.review_like, name='review_like'),
    path('<int:movie_pk>/review/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/review/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
]

movies/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


MAX_RANK = 10

class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'

class Movie(models.Model):
    api_id = models.IntegerField()
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=10)
    poster_path = models.CharField(max_length=100, default='')
    backdrop_path = models.CharField(max_length=100, default='')
    genres = models.ManyToManyField(Genre, related_name='movies')
    trailer = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.title}'

class Review(models.Model):
    rank = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(MAX_RANK)])
    rank_star = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_review')

    def __str__(self):
        return f'{self.movie.title} : {self.rank_star}'
    
    def add_vote(self):
        self.movie.vote_count += 1
        vote_average = self.movie.vote_average
        
        self.movie.vote_average = round(((self.movie.vote_count - 1) * vote_average + self.rank) / self.movie.vote_count, 1)
        self.movie.save()

    def delete_vote(self):
        self.movie.vote_count -= 1
        vote_average = self.movie.vote_average

        try:
            self.movie.vote_average = round(((self.movie.vote_count + 1) * vote_average - self.rank) / (self.movie.vote_count), 1)
        except ZeroDivisionError:
            self.movie.vote_average = 0
        
        self.movie.save()
    
    def update_vote(self, before, after):
        self.movie.vote_average = round((self.movie.vote_average * self.movie.vote_count - before + after) / self.movie.vote_count, 1)
        self.movie.save()
        

movies/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Review, MAX_RANK


class ReviewForm(forms.ModelForm):
    rank = forms.IntegerField(
        label=None,
        widget = forms.NumberInput(
            attrs={
                'id': 'rank',
                'min': 1,
                'max': MAX_RANK,
            },
        ),
        validators=[MinValueValidator(1), MaxValueValidator(MAX_RANK)],
    )
    content = forms.CharField(
        label="댓글",
        max_length=200,
        widget=forms.Textarea(
            attrs={
                'id': 'content',
                'placeholder': '이 영화에 대해 평가해주세요!',
            },
        )
    )
    class Meta:
        model = Review
        fields = ('rank', 'content', )

movies/views.py
import datetime
from dateutil.relativedelta import relativedelta
import random

from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.db.models import Q

from .models import Movie, Genre, Review, MAX_RANK
from .forms import ReviewForm


ALL_MOVIE_COUNT = 2000
RANDOM_MOVIE_COUNT = 10
YEARLY_FAVOR_COUNT = 3

Genres = {
	 "Adventure" : ["모험", "어드벤처"],
	 "Fantasy" : ["판타지"],
	 "Animation" : ["애니"],
	 "Drama" : ["드라마"],
	 "Horror" : ["공포"],
	 "Action" : ["액션"],
	 "Comedy" : ["코미디"],
	 "History" : ["역사"],
	 "Western" : ["서부"],
	 "Thriller" : ["스릴러"],
	 "Crime" : ["범죄"],
	 "Documentary" : ["다큐"],
	 "Science Fiction" : ["SF", "공상"],
	 "Mystery" : ["미스테리", "추리"],
	 "Music" : ["음악"],
	 "Romance" : ["로맨스", "사랑"],
	 "Family" : ["가족", "패밀리"],
	 "War" : ["전쟁"],
	 "TV Movie" : ["티비"], 
}
Genres_pk = {
	 "Adventure" : 12,
	 "Fantasy" : 14,
	 "Animation" :16 ,
	 "Drama" : 18,
	 "Horror" : 27,
	 "Action" : 28,
	 "Comedy" : 35,
	 "History" : 36,
	 "Western" : 37,
	 "Thriller" : 56,
	 "Crime" : 80,
	 "Documentary" : 99,
	 "Science Fiction" : 878,
	 "Mystery" : 9648,
	 "Music" : 10402,
	 "Romance" : 10749,
	 "Family" : 10751,
	 "War" : 10752,
	 "TV Movie" : 10770, 
}

def start(request) : 
    return redirect('movies:main')


def recommend(recents):
    '''
    최근 좋아요 한 영화 기준으로 추천
    1. 장르
    2. 제목
    '''
    # 1.
    # 가장 많이 중복된 장르 추출
    # -> favorite_genres : list
    # 2.
    # 유사한 제목으로 추출
    # 키워드는 보통 앞에 있을거라고 생각하고

    genre_data = dict()
    favorite_genres = []
    keywords = []
    for movie in recents:
        # 1.
        for genre in movie.genres.iterator():
            genre_data[genre] = genre_data.get(genre, 0) + 1
        
        # 2.
        keywords.append(movie.title.split()[0])

    maxcount = 0
    for genre, count in genre_data.items():
        if count > maxcount:
            maxcount = count
            favorite_genres = [genre]
        elif count == maxcount:
            favorite_genres.append(genre)

    genre_recommends = []
    for genre in favorite_genres:
        genre_recommends += random.sample(tuple(genre.movies.all()), RANDOM_MOVIE_COUNT)
    
    # 장르로 뽑은 결과 
    # -> genre_recommends : list
    genre_recommends = Movie.objects.filter(pk__in=[movie.id for movie in random.sample(genre_recommends, RANDOM_MOVIE_COUNT//2)])
    
    # keyword_recommends_with_pk -> keyword로 추출한 영화의 pk list
    # recents_with_pk -> 입력 영화의 pk map
    keyword_recommends_with_pk = []
    for keyword in keywords:
        keyword_recommends_with_pk += map(lambda movie: movie.pk ,Movie.objects.filter(title__startswith=keyword).iterator())
    recents_with_pk = map(lambda movie: movie.pk, recents.iterator())

    # 추출결과에서 이미 추천된 영화는 제외
    keyword_recommends = \
        Movie.objects.filter(pk__in=keyword_recommends_with_pk)\
        .exclude(pk__in=recents_with_pk)


    result = keyword_recommends | genre_recommends

    return result

def main(request):
    # 최신 영화 중 평점 높은 영화 - 인기영화
    
    # 2달전 날짜 - 최신 영화 뽑기 위해
    month_ago = datetime.datetime.now() - relativedelta(months=2)
    popular_movies = Movie.objects.order_by('-popularity').exclude(poster_path="").filter(release_date__lte=datetime.datetime.now(), release_date__gte=month_ago)[:10]
    # 랜덤 영화
    random_movies = Movie.objects.exclude(poster_path="").filter(
        pk__in=list(random.sample(
            range(1, ALL_MOVIE_COUNT+1), RANDOM_MOVIE_COUNT
            ))
        )
    
    # 최근 기록
    # 최근 기록은 user.recents() << method로 사용할것
    if request.user.is_authenticated:
        recents = request.user.recents()
        if recents:
            recommends = recommend(recents).order_by('?')[:RANDOM_MOVIE_COUNT]
        else:
            recommends = Movie.objects.none()
        is_logged_in = True
    else:
        recommends = Movie.objects.none()
        is_logged_in = False


    # 좋아하는 연도 추천영화
    if request.user.is_authenticated:
        yearly_favor = [
            ('under60', request.user.liked_under60),
            ('1960', request.user.liked_1960),
            ('1970', request.user.liked_1970),
            ('1980', request.user.liked_1980),
            ('1990', request.user.liked_1990),
            ('2000', request.user.liked_2000),
            ('2010', request.user.liked_2010),
            ('2020', request.user.liked_2020),
        ]
        LIKED_COUNT = 1

        yearly_favor = sorted(yearly_favor, key=lambda x: x[LIKED_COUNT], reverse=True)

        yearly_favor_movies = Movie.objects.none()
        if yearly_favor[0][1] == 0:
            liked = False

            for year, count in yearly_favor:
                if year == 'under60':
                    movies = Movie.objects.filter(release_date__lt=datetime.date(1960, 1, 1))
                else:
                    year = int(year)
                    movies = Movie.objects.filter(release_date__lt=datetime.date(year + 10, 1, 1)).filter(release_date__gte=datetime.date(year, 1, 1))
                yearly_favor_movies |= movies.order_by('?')[:RANDOM_MOVIE_COUNT//4]
        else:
            liked = True

            for year, count in yearly_favor:
                if year == 'under60':
                    movies = Movie.objects.filter(release_date__lt=datetime.date(1960, 1, 1))
                else:
                    year = int(year)
                    movies = Movie.objects.filter(release_date__lt=datetime.date(year + 10, 1, 1)).filter(release_date__gte=datetime.date(year, 1, 1))
                yearly_favor_movies |= movies.order_by('?')[:RANDOM_MOVIE_COUNT//3]

        recommends |= yearly_favor_movies

    else:
        liked = False

    new_movies = Movie.objects.filter(release_date__gte=month_ago).order_by('?')[:20]

    context = {
        'popular_movies' : popular_movies,
        'movies' : random_movies,
        'new_movies': new_movies,
        'recommends': sorted(recommends, key=lambda x: random.random()),
        'is_logged_in': is_logged_in,
        'liked': liked,
    }
    return render(request, 'movies/main.html', context)

def index(request, sort=None):

    if sort == 'rank':
        movies = Movie.objects.order_by('-vote_average').filter(release_date__lte=datetime.datetime.now())
    elif sort == 'release':
        movies = Movie.objects.order_by('-release_date').filter(release_date__lte=datetime.datetime.now())
    else:
        movies = Movie.objects.order_by('-pk').filter(release_date__lte=datetime.datetime.now())
    paginator = Paginator(movies, 12)
    nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'nowDate': nowDate,
    }
    
    if not page_number or int(page_number) == 1:
        return render(request, 'movies/index.html', context)
    else:
        return render(request, 'movies/index_scroll.html', context)


def search(request, sort):
    input_value = request.GET.get('search')
    if input_value : 
        if sort == 'name' : 
            # 제목으로 검색
            movies = Movie.objects.order_by('-pk').filter(Q(title__icontains=input_value) | 
                                                        Q(original_title__icontains=input_value))
        elif sort == 'genre' : 
            # 장르로 검색
            input_values = input_value.split(' ')
            genres = []
            for val in input_values : 
                for genre in Genres : 
                    if val.lower() == genre.lower() or val in Genres[genre] : 
                        genres.append(Genre.objects.get(name=genre))
            
            if genres : 
                movies = set(Movie.objects.all())
                for genre in genres : 
                    results = set(genre.movies.all())
                    movies = movies.intersection(results)
                movies = list(movies)
            else : movies = None
    else : 
        movies = Movie.objects.order_by('-pk').filter(release_date__lte=datetime.datetime.now())
    
    # paginator
    # print(movies)
    if movies : 
        paginator = Paginator(movies, 8)
        nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
    else : page_obj = None
    context = {
        'input_value' : input_value,
        'page_obj' : page_obj,
    }
    return render(request, 'movies/search.html', context)


@login_required
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    reviews = movie.review_set.order_by('-pk').exclude(author=request.user)
    my_review = movie.review_set.filter(author=request.user)
    nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
    form = ReviewForm()
    is_voted = movie.review_set.filter(author=request.user).exists()
    previous = request.META.get('HTTP_REFERER', '/movies/index/')
    context = {
        'movie': movie,
        'form': form,
        'reviews': reviews,
        'my_review': my_review,
        'is_voted': is_voted,
        'review_count': len(reviews) + len(my_review),
        'previous': previous,
    }
    return render(request, 'movies/detail.html', context)

@login_required
def movie_like(request, movie_pk):
    user = request.user
    movie = get_object_or_404(Movie, pk=movie_pk)

    if movie.liked_users.filter(pk=user.pk).exists():
        movie.liked_users.remove(user)
        liked = False
        user.disliked(movie)
    else:
        movie.liked_users.add(user)
        liked = True
        user.liked(movie)
    context = {
        'movie_liked': liked,
        'count': movie.liked_users.count(),
    }

    return JsonResponse(context)


@login_required
@require_POST
def review_create(request, movie_pk):
    form = ReviewForm(request.POST)

movies/templates/movies/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
MOVIE
{% endblock %}


{% block style %}
<style>
#content{
    resize: none;
    height: 100px;
  }
  

</style>

{% endblock %}

{% block context %}
    <div class="container mt-5">
    <h2>평점 수정</h2>
    <hr>

    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        <button class="w3-button"  style="background-color: #4c6b8d; color:white;">평점 수정</button>
    
    </form>
    </div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
MOVIE
{% endblock %}

{% block style %}
<style>
  #ToTopButton{
      position: fixed;
      right: 2%;
      bottom: 50px;
      display: none;
      z-index: 999;
  }
  .card-body, .movie_title{
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
  .movie_title{
    font-family: "Roboto", sans-serif
    }
  </style>
{% endblock %}


{% block context %}
<!-- TOP BUTTON -->
  <a href="#myPage" title="To Top">
    <i class="w3-button w3-circle fas fa-chevron-up p-3" id="ToTopButton" style="color: white;background-color: #1F618D;"></i>
  </a>
<!-- CONTEXT -->
<div class="container mt-5 mb-5 pb-3 d-flex justify-content-between w3-border-bottom"> 
  <div class="row d-flex flex-fill">
    <h3 class="mr-5"><a href="{% url 'movies:index' %}" class="text-dark"><i class="fas">전체 영화</i></a></h3>
    <!-- Search -->
    <form class="d-flex" action="{% url 'movies:search' 'name' %}" method="GET">
      <input  name="search" class="w3-input w3-border w3-animate-input" placeholder="Search" type="text" required>
      <button class="btn" style="border-style: solid; border-color: #212F3C;">Search</button>
    </form>
  </div>
  <div class="align-self-end">
    {% if request.path == '/movies/index/rank/' %}
    <a href="{% url 'movies:index_sort' 'rank' %}" class="mr-2" style="color: #2E86C1 ;"><i class="fas fa-check">평점순</i></a>
    {% else %}
    <a href="{% url 'movies:index_sort' 'rank' %}" class="mr-2 text-muted"><i class="fas fa-check">평점순</i></a>
    {% endif %}
    {% if request.path == '/movies/index/release/' %}
    <a href="{% url 'movies:index_sort' 'release' %}" class="mr-2" style="color: #2E86C1;"><i class="fas fa-check">개봉순</i></a>
    {% else %}
    <a href="{% url 'movies:index_sort' 'release' %}" class="mr-2 text-muted"><i class="fas fa-check">개봉순</i></a>
    {% endif %}
  </div>    
</div>

<!-- 영화 목록 - poster_path, adult, title, vote_average, released_date -->
<div class="container" id="Total_movie">
  <div class="row" id="movie_list">
    {% for movie in page_obj %}
      <div class="col-12 col-md-6 col-lg-4 col-xl-3 mb-3 movie_card">
        <div class="card h-100">
          <!-- 영화 이미지 -->
          <a href="{% url 'movies:detail' movie.pk %}">
            {% if movie.poster_path %}
            <img src="https://image.tmdb.org/t/p/w342/{{ movie.poster_path }}" alt="{{ movie.title }}" class=" card-img-top ReSizeImage">
            {% else %}
            <img src="{% static 'image/noimage_index.png' %}" alt="{{ movie.title }}" class=" card-img-top ReSizeImage border border-gray">
            {% endif %}
          </a>
        
          <!-- 영화 제목, 좋아요, 평점, 개봉일 -->
          <div class="card-body">
            <!-- 영화 제목 -->
            <a href="{% url 'movies:detail' movie.pk %}" ><h5 class="font-weight-bold text-dark movie_title" >{{ movie.title }}</h5></a>
            <!-- 개봉일 -->
            <p class="mt-2 mb-0"><small>{{ movie.release_date|date:"Y-m-d" }} 개봉</small></p>
            <hr>
            <div class="container-fluid">
              <div class="d-flex justify-content-between pt-3 ">
                  <!-- 영화 평점 -->
                  <div>
                  <span><i class="fas fa-star fa-lg" style="color:crimson">{{ movie.vote_average }}</i></span>
                  </div>
                  <!-- 영화 좋아요 -->
                  <div>
                    {% if request.user in movie.liked_users.all %}
                      {% if request.user.is_authenticated %}
                          <i class="fas fa-heart like-button fa-lg align-self-center" style="color:crimson" data-id="{{ movie.pk }}"></i>
                      {% else %}
                          <i class="fas fa-heart fa-lg align-self-center" style="color:crimson" onclick="alert('로그인이 필요합니다.')"></i>
                      {% endif %}
                    {% else %}
                      {% if request.user.is_authenticated %}
                          <i class="fas fa-heart like-button fa-lg align-self-center" style="color:black" data-id="{{ movie.pk }}"></i>
                      {% else %}
                          <i class="fas fa-heart fa-lg align-self-center" style="color:black" onclick="alert('로그인이 필요합니다.')"></i>
                      {% endif %}
                    {% endif %}
                    <span id="like-count-{{ movie.pk }}">{{ movie.liked_users.all|length }}</span>
                  </div>
              </div>
            </div>
          </div>
      
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<!-- Pagination -->

<script>
  
$(document).ready(function(){
  // 무한스크롤
    const BASEURL = $(location).attr('pathname')  
    var page = 1
    console.log($(window).scrollTop())
    console.log($('#Main_Context').outerHeight())
    $(window).scroll(function() {
        if ($(window).outerHeight() >= $('#Main_Context').outerHeight() || $(window).scrollTop() >= $(document).height() - $(window).height() - 2) {
          page++
          axios.get(BASEURL + `?page=${page}`)
          .then((res) => {
            $('#movie_list').append(res.data)
          })
        }
    });
    // TOP BUTTON
    $(window).scroll(function() {
        
          if ($(this).scrollTop() > 500) {
              $('#ToTopButton').fadeIn();
          } else {
              $('#ToTopButton').fadeOut();
          }
      });


    $("#ToTopButton").click(function(event) {
        $('html, body').animate({
            scrollTop: 0
        }, 400);
        return false
    })

    // searchbar
    // $("#SearchButton").click(function() {
    //   var inputValue = $("#mySearch").val()
    //   axios.get(`/movies/index/search/${inputValue}/`)
    //   .then((res) => {
    //     $("#Total_movie").html(res.data)

    //   })
    // })
    $("#mySearch").keydown(function(key) {
      if (key.keyCode == 13){
        var inputValue = $("#mySearch").val()
        axios.get(`/movies/index/search/${inputValue}/`)
        .then((res) => {
          $("#Total_movie").html(res.data)
        })
      }
    })


    // 이미지 사이즈 조절
    $('.ReSizeImage').each(function(){
        var width = $(this).innerWidth()
        console.log($(this).html(), width)
        var ratio = 1.5
        $(this).innerHeight(width*ratio)
    })
    $(window).resize(function(){
      $('.ReSizeImage').each(function(){
            var width = $(this).innerWidth()
            var ratio = 1.5
            $(this).innerHeight(width*ratio)
          })
      var title_height = 0
      
      })
    })
  // 좋아요
    $('.fa-heart').on('click',function(event){
      const movieId = event.target.dataset.id
      if (movieId !== undefined) {
        axios.get(`/movies/${movieId}/like/`)

        .then((response) => {
          // response.data.count -> json으로 응답(해당 게시글에 좋아요를 누른 사람의 수)
          document.querySelector(`#like-count-${movieId}`).innerText = response.data.count

          if (response.data.movie_liked) {
            event.target.style.color = 'crimson'
          } else {
            event.target.style.color = 'black'
          }
        })
        .catch((error) => {
          console.log(error)
        })
      }
    })
  </script>
{% endblock %}

movies/templates/movies/index_ajax.html
{% load static %}
{% load bootstrap4 %}

{% for movie in page_obj %}
<div class="col-12 col-md-6 col-lg-3 mb-3">
  <div class="card h-100">
  <!-- 영화 이미지 -->
    <a href="{% url 'movies:detail' movie.pk %}">
      {% if movie.poster_path %}
      <img src="https://image.tmdb.org/t/p/w342/{{ movie.poster_path }}" alt="{{ movie.title }}" class=" card-img-top ReSizeImage">
      {% else %}
      <img src="{% static 'image/noimage_index.png' %}" alt="{{ movie.title }}" class=" card-img-top ReSizeImage">
      {% endif %}
    </a>
    <!-- 영화 제목, 좋아요, 평점, 개봉일 -->
    <div class="card-body">
      <div class="d-flex justify-content-between">
          <div>
            <!-- 영화 제목, 평점 -->
            <a href="{% url 'movies:detail' movie.pk %}" class="font-weight-bold">{{ movie.title }}</a>
            <span><i class="fas fa-star fa-sm" style="color:crimson"> {{ movie.vote_average }}</i></span>
          </div>
          <div>
            <!-- 영화 좋아요 -->
          {% if request.user in movie.liked_users.all %}
              <i class="fas fa-heart fa-lg like-button" style="color:crimson" data-id="{{ movie.pk }}"></i>
              <span id="like-count-{{ movie.pk }}">{{ movie.liked_users.all|length }}</span>
          {% else %}
              <i class="fas fa-heart fa-lg like-button" style="color:black" data-id="{{ movie.pk }}"></i>
              <span id="like-count-{{ movie.pk }}">{{ movie.liked_users.all|length }}</span>
          {% endif %}
          </div>
      </div>
      <!-- 개봉일 -->
      <p class="mt-2 mb-0"><small>{{ movie.release_date|date:"Y-m-d" }} 개봉</small></p>
        
    </div>

  </div>
</div>
{% endfor %}
<script>
      $(document).ready(function(){
        $('.ReSizeImage').each(function(){
            var width = $(this).innerWidth()
            var ratio = 1.5
            console.log(width, width*ratio)
            console.log($(this).innerHeight())
            $(this).innerHeight(width*ratio)
            console.log($(this).innerHeight())

        })
    })
</script>