community/urls.py
from django.urls import path
from . import views


app_name = 'community'

urlpatterns = [
    path('', views.community, name='community'),
    path('create/', views.create_article, name='create_article_noboard'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    path('<int:article_pk>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/update/', views.update_comment, name='update_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('<str:board_name>/', views.board, name='board'),
    path('<str:board_name>/create/', views.create_article, name='create_article'),
]

movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('', views.start),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.index, name='index'),
    path('search/<str:sort>/', views.search, name="search"),
    path('index/<str:sort>/', views.index, name='index_sort'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'),
    path('<int:movie_pk>/review/create/', views.review_create, name='review_create'),
    path('<int:movie_pk>/review/<int:review_pk>/like/', views.review_like, name='review_like'),
    path('<int:movie_pk>/review/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/review/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
]

community/models.py
import pytz
from faker import Faker

from django.db import models
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.utils import timezone


class Board(models.Model):
    name = models.CharField(max_length=100)
    url_name = models.CharField(max_length=100)
    auth_required = models.BooleanField(default=False)
    name_short = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.name}'

    @classmethod
    def init(cls):
        board_data = [
            {
                'name': '공지사항',
                'url_name': 'notice',
                'name_short': '공지',
                'auth_required': True,
            },
            {
                'name': '자유게시판',
                'url_name': 'free',
                'name_short': '자유',
            },
            {
                'name': '추천게시판',
                'url_name': 'recommend',
                'name_short': '추천',
            },
        ]
        for board in board_data:
            Board.objects.create(**board)
        

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField()
    updated = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    hits = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title}'

    def hit(self):
        self.hits += 1
        self.save()

    def dummy(count):
        faker = Faker('ko-KR')
        if Board.objects.count() == 0:
            Board.objects.create(name="testboard")
        if get_user_model().objects.count() == 0:
            get_user_model().objects.create(
                username=faker.name(),
                password="1"
            )
        for _ in range(count):
            Article.objects.create(
                title=faker.sentence(),
                content=str(faker.text()) * 10,
                author=get_user_model().objects.get(pk=1),
                board=Board.objects.get(pk=3),
                updated_at=timezone.now()
            )

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

community/forms.py
from django import forms

from .models import Article, Comment, Board


class ArticleForm(forms.ModelForm):
    board = forms.ModelChoiceField(queryset=Board.objects.filter(auth_required=False))
    class Meta:
        model = Article
        fields = ('title', 'content', 'board')

class AdminArticleForm(ArticleForm):
    board = forms.ModelChoiceField(queryset=Board.objects.all())
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="댓글",
        max_length=200,
        widget=forms.Textarea(
            attrs={
                'id': 'content',
                'placeholder': '댓글',
            },
        )
    )
    class Meta:
        model = Comment
        fields = ('content', )

community/views.py
import datetime # 날짜 가져오기
import pytz

from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.utils import timezone

from .models import Article, Comment, Board
from .forms import ArticleForm, CommentForm, AdminArticleForm


NOTICE_BOARD_NAME = '공지사항'
MAX_NOTICE_COUNT = 3

def community(request):
    boards = Board.objects.all()
    notice_board = Board.objects.get(name=NOTICE_BOARD_NAME)
    noticed = notice_board.article_set.order_by('-pk')
    if len(noticed) >= 3:
        noticed = noticed[:3]
    articles = Article.objects.order_by('-pk').exclude(board=notice_board)

    paginator = Paginator(articles, 10)
    nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    boards = Board.objects.all()
    context = {
        'page_obj': page_obj,
        'nowDate': nowDate,
        'board': None,
        'boards': boards,
        'noticed': noticed,
    }

    return render(request, 'community/index.html', context)


def board(request, board_name=None):
    notice_board = Board.objects.get(name=NOTICE_BOARD_NAME)
    noticed = notice_board.article_set.order_by('-pk')
    if len(noticed) >= 3:
        noticed = noticed[:3]
    if board_name is None:
        board = None
        articles = Article.objects.order_by('-pk').exclude(board=notice_board)
    else:
        board = get_object_or_404(Board, url_name=board_name)
        articles = board.article_set.order_by('-pk')

    paginator = Paginator(articles, 10)
    nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    boards = Board.objects.all()
    context = {
        'page_obj': page_obj,
        'nowDate': nowDate,
        'now_board': board,
        'boards' : boards,
        'noticed' : noticed,
    }
    return render(request, 'community/index.html', context)


@login_required
def create_article(request, board_name=None):
    if request.method == 'POST':
        if request.user.is_superuser:
            form = AdminArticleForm(request.POST)
        else:
            form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.board = get_object_or_404(Board, pk=request.POST.get('board')[0])
            article.updated_at = timezone.now()
            article.save()
            return redirect('community:detail', article.pk)
    else:
        board = get_object_or_404(Board, url_name=board_name)
        if board.auth_required and not request.user.is_superuser:
            messages.error(request, '관리자만 접근 가능합니다.')
            #
            if board_name is None:
                board = None
                articles = Article.objects.order_by('-pk')
            else:
                board = get_object_or_404(Board, url_name=board_name)
                articles = board.article_set.all()

            paginator = Paginator(articles, 10)
            nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            boards = Board.objects.all()
            context = {
                'page_obj': page_obj,
                'nowDate': nowDate,
                'now_board': board,
                'boards' : boards,
            }
            return render(request, 'community/index.html', context)
            #
        else:
            if board_name:
                board = Board.objects.get(url_name=board_name)
                if request.user.is_superuser:
                    form = AdminArticleForm(initial={'board': board})
                else:
                    form = ArticleForm(initial={'board': board})
            else:
                if request.user.is_superuser:
                    form = AdminArticleForm()
                else:
                    form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)


@login_required
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    article.hit()
    comments = article.comment_set.order_by('-pk')
    nowDate = datetime.datetime.now().strftime('%Y-%m-%d')
    form = CommentForm()
    previous = request.META.get('HTTP_REFERER', f'/community/{article.board.url_name}/')
    if (request.META.get('HTTP_REFERER').split('/')[-2] == 'community'):
        previous_name = '전체게시판'
    else:
        previous_name = article.board.name
    # previous_name = 
    context = {
        'form': form,
        'article': article,
        'comments' : comments,
        'nowDate': nowDate,
        'previous': previous,
        'previous_name': previous_name,
    }
    return render(request, 'community/detail.html', context)


@login_required
def update_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        if request.user.is_superuser:
            form = AdminArticleForm(request.POST, instance=article)
        else:
            form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article.updated_at = timezone.now()
            article.updated = True
            article = form.save()
            return redirect('community:detail', article_pk)
    else:
        if request.user != article.author:
            return redirect('community:detail', article_pk)
        if request.user.is_superuser:
            form = AdminArticleForm(instance=article)
        else:
            form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)


@login_required
def article_like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)

    if article.liked_users.filter(pk=user.pk).exists():
        article.liked_users.remove(user)
        liked = False
    else:
        article.liked_users.add(user)
        liked = True
    
    context = {
        'article_liked': liked,
        'count': article.liked_users.count(),
    }

    return JsonResponse(context)

@login_required
@require_POST
def delete_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    url_name = article.board.url_name
    if request.user == article.author:
        article.delete()
        return redirect('community:board', board_name=url_name)
    return redirect('community:detail', article_pk)


@login_required
def create_comment(request, article_pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.article = get_object_or_404(Article, pk=article_pk)
        comment.save()
    return redirect('community:detail', article_pk)

@login_required
def update_comment(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)

    if request.user != comment.author:
        return redirect('community:detail', article_pk)
        
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.updated = True
            comment.save()
            return redirect('community:detail', article_pk)
    else:
        form = CommentForm(instance=comment)
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)

@login_required
@require_POST
def delete_comment(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.author:
        comment.delete()
    return redirect('community:detail', article_pk)


@login_required
def comment_like(request, article_pk, comment_pk):
    user = request.user
    comment = get_object_or_404(Comment, pk=comment_pk)

    if comment.liked_users.filter(pk=user.pk).exists():
        comment.liked_users.remove(user)
        liked = False
    else:
        comment.liked_users.add(user)
        liked = True
    
    context = {
        'comment_liked': liked,
        'count': comment.liked_users.count(),
    }

    return JsonResponse(context)

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}COMMUNITY{% endblock %}

{% block style %}
<style>
#content{
    resize: none;
    height: 80px;
  }
  

</style>

{% endblock %}


{% block context %}
<div class="container mt-5">
    <div class="d-flex justify-content-between"> 
        <h5>
            <a href="{{ previous }}" class="text-dark"><i class="fas fa-angle-double-left"></i></a>
            <!-- <a href="{%url 'community:community' %}" class="text-dark">커뮤니티</a> -->
            <i class="fas"> {{ previous_name }} </i>
        </h5>
    </div>
    <hr class="mt-2 mb-3">

    <!-- 게시글 -->
    <div>
        <div class="d-flex justify-content-between">
            <h4 class="font-weight-bold mb-3">{{ article.title }}</h4>
            <div>
                {% if request.user in article.liked_users.all %}
                    <span><i class="fas fa-star fa-lg like-article-button" style="color: rgb(31, 185, 0)" data-id="{{ article.pk }}"></i></span>
                    <small id="like-article-count-{{ article.pk }}" style="color:black">(스크랩 : {{ article.liked_users.all|length }})</small>
                                    
                {% else %}
                    <span><i class="fas fa-star fa-lg like-article-button" style="color:black" data-id="{{ article.pk }}"></i></span>
                    <small id="like-article-count-{{ article.pk }}" style="color:black">(스크랩 : {{ article.liked_users.all|length }})</small>
                    
                {% endif %}
                </div>
        </div>
        <div class="d-flex justify-content-between">
            <div class="d-flex flex-column">
                <p class="text-muted m-0"><small>{{ article.created_at }} 작성</small></p>
                {% if article.updated %}
                <p class="text-muted m-0"><small>{{ article.updated_at }} 수정</small></p>
                {% endif %}
            </div>
            <div>
                <span class="text-muted mx-2"><small>조회 수 {{ article.hits }}</small></span>
                <span class="text-muted"><small>댓글 수 {{ comments|length }}</small></span>
                
            </div>
            

            
        </div>
        <hr class="mt-0 mb-3">
        <p>{{ article.content }}</p>
        <!-- 게시글 수정&삭제 버튼 -->
        <div class="d-flex justify-content-end">
        {% if article.author == request.user %}
            <small><a href="{% url 'community:update_article' article.pk %}" class="text-dark">수정</a></small>
            <small>
                <form action="{% url 'community:delete_article' article.pk %}" method="POST" class="d-inline">
                    {% csrf_token %}
                <button style="border:0; background-color: transparent" class="text-decoration-none">삭제</button>
                </form>
            </small>
        {% endif %}
        </div>
    </div>
    

    <!-- 댓글 -->
    <hr>
    <!-- 댓글 작성 -->
    <form action="{% url 'community:create_comment' article.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-flex justify-content-end">
        <button id="submit" class="w3-button"  style="background-color: #4c6b8d; color:white;">댓글 작성</button>
        </div>
    </form>


    <!-- 댓글 목록 -->
    <p class="mt-4"><strong>{{ comments|length }}</strong>개의 댓글</p>
    <hr>
    {% for comment in comments %}
        <!-- 날짜 & 댓글 수정, 삭제 -->
        <div class="d-flex justify-content-between">
        <p>{{ comment.author }} 
            <small class="text-muted"> 
                {% if comment.updated_at|date:"Y-m-d" == nowDate %}
                    | {{ comment.updated_at | date:"H:i" }}
                {% else %}
                    | {{ comment.updated_at | date:"Y-m-d" }}
                {% endif %}
            </small>
        </p>
        {% if comment.author == request.user %}
        <div>
            <!-- <small><a href="{% url 'community:update_comment' article.pk comment.pk %}" class="text-dark">수정</a></small> -->
            {% if comment.updated %}
            <small class="text-muted">{{ comment.updated_at }} (수정됨)</small>
            {% endif %}
            <small><a href="{% url 'community:update_comment' article.pk comment.pk %}" class="text-dark">수정</a></small>
            <small>
                <form action="{% url 'community:delete_comment' article.pk comment.pk %}" method="POST" class="d-inline">
                    {% csrf_token %}
                <button style="border:0; background-color: transparent" class="text-decoration-none">삭제</button>
                </form>
            </small>
        </div>
        {% endif %}
        </div>
        <p>{{ comment.content }}</p>
        {% if request.user in comment.liked_users.all %}
            <span><i class="far fa-thumbs-up fa-lg like-comment-button" style="color: #0077ff" data-id="{{ comment.pk }}" data-article-id="{{ article.pk }}"></i></span>
            <small id="like-comment-count-{{ comment.pk }}" style="color:black">{{ comment.liked_users.all|length }}</small>
        {% else %}
            <span><i class="far fa-thumbs-up fa-lg like-comment-button" style="color:black" data-id="{{ comment.pk }}" data-article-id="{{ article.pk }}"></i></i></span>
            <small id="like-comment-count-{{ comment.pk }}" style="color:black">{{ comment.liked_users.all|length }}</small>
        {% endif %}
        <hr>
    {% empty %}
        <p>새 댓글을 써주세요!</p>
    {% endfor %}

</div>
<script>

    const likeArticleButton = document.querySelector('.like-article-button')
    const likeCommentButtonList = document.querySelectorAll('.like-comment-button')
    
    
    likeArticleButton.addEventListener('click', function(event){
    const articleId = event.target.dataset.id

    axios.get(`/community/${articleId}/like/`)
    .then((response) => {
        
        // response.data.count -> json으로 응답(해당 게시글에 좋아요를 누른 사람의 수)
        document.querySelector(`#like-article-count-${articleId}`).innerText = "(스크랩 : " + response.data.count + ")"
        console.log(response.data)
        if (response.data.article_liked) {
        event.target.style.color = 'rgb(31, 185, 0)'
        } else {
        event.target.style.color = 'black'
        }
    })
    .catch((error) => {
        console.log(error)
    })
    })

    likeCommentButtonList.forEach((likeButton) => {
        likeButton.addEventListener('click', function(event){
        const commentId = event.target.dataset.id
        const articleId = event.target.dataset.articleId
    
        axios.get(`/community/${articleId}/comment/${commentId}/like/`)
    
        .then((response) => {
            // response.data.count -> json으로 응답(해당 게시글에 좋아요를 누른 사람의 수)
            document.querySelector(`#like-comment-count-${commentId}`).innerText = response.data.count
            console.log(response.data)
            if (response.data.comment_liked) {
            event.target.style.color = '#0077ff'
            } else {
            event.target.style.color = 'black'
            }
        })
        .catch((error) => {
            console.log(error)
        })
        })
    })
</script>

{% endblock %}

community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}COMMUNITY{% endblock %}


{% block style %}
<style>
#content{
    resize: none;
    height: 100px;
  }
  

</style>

{% endblock %}

{% block context %}
<div class="conatiner mt-5 px-5">
    {% if request.resolver_match.url_name == 'create_article' or request.resolver_match.url_name == 'create_article_noboard' %}
    <h2>게시글 작성</h2>
    {% elif request.resolver_match.url_name == 'update_article' %}
    <h2>게시글 수정</h2>
    {% elif request.resolver_match.url_name == 'update_comment' %}
    <h2>댓글 수정</h2>
    {% endif %}
    <hr>

    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% if request.resolver_match.url_name == 'create_article' %}
            <button class="w3-button "  style="background-color: #4c6b8d; color:white;">게시글 작성</button>
        {% elif request.resolver_match.url_name == 'update_article' %}
            <button class="w3-button" style="background-color: #4c6b8d; color:white;">게시글 수정</button>
        {% else %}
        <button class="w3-button" style="background-color: #4c6b8d; color:white;">댓글 수정</button>
        {% endif %}
    
    </form>
</div>
{% endblock %}

community/templates/community/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block title %}COMMUNITY{% endblock %}

{% block style %}
<style>
    .page-link{
        border-style: none;
        color: black;
    }
    .page-item.active .page-link {
    z-index: 1;
    color: #fff;
    background-color: #314357;
}
</style>
{% endblock %}


{% block context %}
<div class="container mt-5">
    <div class="w3-bar mb-3 d-flex justify-content-between">
        <div class="flex-fill">
        {% if request.path == '/community/' %}
            <a href="{% url 'community:community' %}" class="w3-bar-item w3-mobile text-dark text-decoration-none">
                <h5><strong>전체게시판</strong></h5>
             </a>
        {% else %}
            <a href="{% url 'community:community' %}" class="w3-bar-item w3-mobile text-muted text-decoration-none">
                <h5>전체게시판</h5> 
            </a>
        {% endif %}
        {% for board in boards %}
            <a href="{% url 'community:board' board.url_name %}" class="w3-bar-item w3-mobile text-muted text-decoration-none url_banner">
                <h5>{{ board.name }}</h5>
            </a> 
        {% endfor%}
        </div>
        <div class="align-self-center">
            <!-- <i class="fas fa-search"> | </i> -->
            {% if now_board %}
                {% if now_board.name == '공지사항' and request.user.is_superuser %}
                    <a href="{% url 'community:create_article' now_board.url_name %}" class="text-dark">
                        <h5><i class="fas fa-edit"></i></h5></a>
                {% elif now_board.name != '공지사항' %}
                    <a href="{% url 'community:create_article' now_board.url_name %}" class="text-dark">
                    <h5><i class="fas fa-edit"></i></h5></a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    
    <div class="container mt-0 p-1">
        <hr class="my-2">
        <div class="row" >
            <div class="col-1 text-center">번호</div>
            {% if not now_board %}
            <div class="col-1 text-center">분류</div>
            <div class="col-4 text-center">제목</div>
            {% else %}
            <div class="col-5 text-center">제목</div>
            {% endif %}
            <div class="col-2 text-center">작성자</div>
            <div class="col-2 text-center">조회 수</div>
            <div class="col-2 text-center">작성일</div>
        </div>
        <hr class="my-2">
        <tbody>
            {% if not now_board or now_board.name != '공지사항' %}
            {% for notice in noticed %}
            <div class="row">
                {% if not now_board %}
                <div class="col-1 text-center font-weight-bold">{{ notice.pk }}</div>
                <div class="col-1 text-center font-weight-bold">{{ notice.board.name_short }}</div>
                <div class="col-4">
                    <a href="{% url 'community:detail' notice.pk %}" class="text-dark article_title font-weight-bold">
                        {{notice.title}}
                    </a>
                </div>
                {% else %}
                <div class="col-1 text-center font-weight-bold">{{ notice.board.name_short }}</div>
                <div class="col-5">
                    <a href="{% url 'community:detail' notice.pk %}" class="text-dark article_title font-weight-bold">
                        {{notice.title}}
                    </a>
                </div>
                {% endif %}
                <!-- <div class="col-1 text-center">공지</div>
                <div class="col-5">
                    <a href="{% url 'community:detail' notice.pk %}" class="text-dark article_title">
                        {{notice.title}}
                    </a>
                </div> -->
                <div class="col-2 text-center font-weight-bold">{{ notice.author }}</div>
                <div class="col-2 text-center font-weight-bold">{{ notice.hits }}</div>
                <div class="col-2 text-center font-weight-bold">
                    <!-- 오늘 날짜면 시간만 / 아니면 날짜 출력 -->
                    {% if notice.created_at|date:"Y-m-d" == nowDate %}
                        {{ notice.created_at | date:"H:i" }}
                    {% else %}
                        {{ notice.created_at | date:"Y-m-d" }}
                    {% endif %}
                </div>
            </div>
            <hr class="my-2">
            {% endfor %}
            {% endif %}
            {% if page_obj %}
                {% for article in page_obj %}
                    <div class="row">
                        <div class="col-1 text-center">{{ article.pk }}</div>
                        {% if not now_board %}
                        <div class="col-1 text-center">{{ article.board.name_short }}</div>
                        <div class="col-4">
                            <a href="{% url 'community:detail' article.pk %}" class="text-dark article_title">
                                {{article.title}}
                            </a>
                        </div>
                        {% else %}
                        <div class="col-5">
                            <a href="{% url 'community:detail' article.pk %}" class="text-dark article_title">
                                {{article.title}}
                            </a>
                        </div>
                        {% endif %}
                        <div class="col-2 text-center">{{ article.author }}</div>
                        <div class="col-2 text-center">{{ article.hits }}</div>
                        <div class="col-2 text-center">
                            <!-- 오늘 날짜면 시간만 / 아니면 날짜 출력 -->
                            {% if article.created_at|date:"Y-m-d" == nowDate %}
                                {{ article.created_at | date:"H:i" }}
                            {% else %}
                                {{ article.created_at | date:"Y-m-d" }}
                            {% endif %}
                        </div>
                    </div>
                    <hr class="my-2">
                    
                {% endfor %}
            {% else %}
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center">아직 새로운 글이 올라오지 않았어요</div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                <div class="col-12 text-center whitespace"></div>
                
            {% endif %}
        </tbody>
    </div>
    
    <!-- pagination -->
    <div class="d-flex justify-content-center">
    {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
    
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const whitespace = '\u00A0'
    $(document).ready(function() {
        const URL = $(location).attr('pathname')
        $(".url_banner").each(function(){
            var board_name = $(this).text()
            console.log(board_name)
            if ($(this).attr('href') ==  URL) {
                $(this).html("<h5><strong>"+board_name+"</strong></h5>")
                $(this).removeClass("text-muted")
                $(this).addClass("text-dark")
            }
        
            
        })



        // 제목 줄이기
        const ContextHeight = $('#Main_Context').outerHeight()
        const LengthLimit = 30
        $(".article_title").each(function(){
            var title = $.trim($(this).text())
            if (title.length > 30){
                title = title.substring(1, LengthLimit) + '...'
                $(this).text(title)
            }
        })
        
    })
    $('.whitespace').text(whitespace)
</script>
{% endblock %}