accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
]

community/urls.py
from django.urls import path
from . import views


app_name = 'community'

urlpatterns = [
    path('', views.community, name='community'),
    path('create/', views.create_article, name='create_article_noboard'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    path('<int:article_pk>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/update/', views.update_comment, name='update_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('<str:board_name>/', views.board, name='board'),
    path('<str:board_name>/create/', views.create_article, name='create_article'),
]

movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('', views.start),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.index, name='index'),
    path('search/<str:sort>/', views.search, name="search"),
    path('index/<str:sort>/', views.index, name='index_sort'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'),
    path('<int:movie_pk>/review/create/', views.review_create, name='review_create'),
    path('<int:movie_pk>/review/<int:review_pk>/like/', views.review_like, name='review_like'),
    path('<int:movie_pk>/review/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/review/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from community.models import Article, Comment
from movies.models import Movie


MAX_RECENTS = 3

class CustomUser(AbstractUser):
    liked_articles = models.ManyToManyField(Article, related_name='liked_users')
    liked_movies = models.ManyToManyField(Movie, related_name='liked_users')
    liked_comments = models.ManyToManyField(Comment, related_name='liked_users')

    # 본인 데이터
    # 연도별 ..
    liked_under60 = models.IntegerField(default=0)
    liked_1960 = models.IntegerField(default=0)
    liked_1970 = models.IntegerField(default=0)
    liked_1980 = models.IntegerField(default=0)
    liked_1990 = models.IntegerField(default=0)
    liked_2000 = models.IntegerField(default=0)
    liked_2010 = models.IntegerField(default=0)
    liked_2020 = models.IntegerField(default=0)

    
    # 장르별 ..
    liked_adventure = models.IntegerField(default=0)
    liked_fantasy = models.IntegerField(default=0)
    liked_animation = models.IntegerField(default=0)
    liked_drama = models.IntegerField(default=0)
    liked_horror = models.IntegerField(default=0)
    liked_action = models.IntegerField(default=0)
    liked_comedy = models.IntegerField(default=0)
    liked_history = models.IntegerField(default=0)
    liked_western = models.IntegerField(default=0)
    liked_thriller = models.IntegerField(default=0)
    liked_crime = models.IntegerField(default=0)
    liked_documentary = models.IntegerField(default=0)
    liked_sciencefiction = models.IntegerField(default=0)
    liked_mystery = models.IntegerField(default=0)
    liked_music = models.IntegerField(default=0)
    liked_romance = models.IntegerField(default=0)
    liked_family = models.IntegerField(default=0)
    liked_war = models.IntegerField(default=0)
    liked_tvmovie = models.IntegerField(default=0)

    liked_recents = models.CharField(max_length=50, default='')

    def liked(self, movie):
        year = movie.release_date.year
        if year < 1960:
            self.liked_under60 += 1
        elif year < 1970:
            self.liked_1960 += 1
        elif year < 1980:
            self.liked_1970 += 1
        elif year < 1990:
            self.liked_1980 += 1
        elif year < 2000:
            self.liked_1990 += 1
        elif year < 2010:
            self.liked_2000 += 1
        elif year < 2020:
            self.liked_2010 += 1
        else:
            self.liked_2020 += 1
        
        for genre in movie.genres.all():
            attrname = f'liked_{"".join(genre.name.lower().split())}'
            value = getattr(self, attrname)
            setattr(self,attrname, value + 1)

        recents_data = self.liked_recents.split()

        if len(recents_data) == MAX_RECENTS:
            recents_data.pop(0)
        recents_data.append(str(movie.pk))

        self.liked_recents = ' '.join(recents_data)
        self.save()
    
    def disliked(self, movie):
        year = movie.release_date.year
        if year < 1960:
            self.liked_under60 -= 1
        elif year < 1970:
            self.liked_1960 -= 1
        elif year < 1980:
            self.liked_1970 -= 1
        elif year < 1990:
            self.liked_1980 -= 1
        elif year < 2000:
            self.liked_1990 -= 1
        elif year < 2010:
            self.liked_2000 -= 1
        elif year < 2020:
            self.liked_2010 -= 1
        else:
            self.liked_2020 -= 1
        
        for genre in movie.genres.all():
            attrname = f'liked_{"".join(genre.name.lower().split())}'
            value = getattr(self, attrname)
            setattr(self,attrname, value - 1)
        
        recents_data = self.liked_recents.split()

        if str(movie.pk) in recents_data:
            recents_data.remove(str(movie.pk))

        self.liked_recents = ' '.join(recents_data)
        self.save()
    
    def recents(self):
        recents_data = self.liked_recents.split()
        result = Movie.objects.filter(pk__in=recents_data)
        return result

community/models.py
import pytz
from faker import Faker

from django.db import models
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.utils import timezone


class Board(models.Model):
    name = models.CharField(max_length=100)
    url_name = models.CharField(max_length=100)
    auth_required = models.BooleanField(default=False)
    name_short = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.name}'

    @classmethod
    def init(cls):
        board_data = [
            {
                'name': '공지사항',
                'url_name': 'notice',
                'name_short': '공지',
                'auth_required': True,
            },
            {
                'name': '자유게시판',
                'url_name': 'free',
                'name_short': '자유',
            },
            {
                'name': '추천게시판',
                'url_name': 'recommend',
                'name_short': '추천',
            },
        ]
        for board in board_data:
            Board.objects.create(**board)
        

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField()
    updated = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    hits = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title}'

    def hit(self):
        self.hits += 1
        self.save()

    def dummy(count):
        faker = Faker('ko-KR')
        if Board.objects.count() == 0:
            Board.objects.create(name="testboard")
        if get_user_model().objects.count() == 0:
            get_user_model().objects.create(
                username=faker.name(),
                password="1"
            )
        for _ in range(count):
            Article.objects.create(
                title=faker.sentence(),
                content=str(faker.text()) * 10,
                author=get_user_model().objects.get(pk=1),
                board=Board.objects.get(pk=3),
                updated_at=timezone.now()
            )

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', )

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.views.decorators.http import require_POST

from .forms import CustomUserCreationForm, CustomUserChangeForm


User = get_user_model()

@login_required
def profile(request):
    user = request.user
    movies = user.liked_movies.all()
    if user.liked_movies.all().exists() : 
        context = {
            'user': user,
            'movies' : movies,
            'first_movie' : movies[0],
            'rest_movies' : movies[1:],
            'movie_count': len(movies),
        }
    else : 
        context = {
            'user' : user,
            'movies' : movies,
        }

    return render(request, 'accounts/profile.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'movies:main')
    else:
        form = AuthenticationForm(request)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:main')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:main')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

@login_required
@require_POST
def delete(request):
    user = request.user
    user.delete()
    return redirect('movies:main')

@login_required
def change_password(request):
    if request.method == 'POST':
        user = request.user
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<!-- Page Title -->
{% block title %}
{% if request.resolver_match.url_name == 'signup' %}
    SIGNUP 
{% elif request.resolver_match.url_name == 'login' %}
    LOGIN  
{% elif request.resolver_match.url_name == 'update' %}
    PROFILE
{% else %}
    PROFILE
{% endif %}
{% endblock %}


<!-- Context -->
{% block context %}

<!-- Modal -->
<class class="modal fade" id="UserDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">삭제</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        탈퇴 시, 해당 계정으로 등록한 모든 데이터가 삭제됩니다.<br>
        정말로 탈퇴하시겠습니까?
    </div>
    <div class="modal-footer">
        <button type="button" class="w3-button btn-secondary" data-dismiss="modal">취소</button>
        <a class="w3-button btn-danger w3-hover-red btn-md text-decoration-none" href="{% url 'accounts:delete' %}" role="button">삭제</a>
    </div>
    </div>
</div>
</class>


<div class="container border border-secondary rounded p-4 mt-5">
{% if request.resolver_match.url_name == 'signup' %}
    <h2>회원가입</h2>
{% elif request.resolver_match.url_name == 'login' %}
    <h2>로그인</h2>
{% elif request.resolver_match.url_name == 'update' %}
    <h2>회원 정보 수정</h2>
{% else %}
    <h2>비밀번호 변경</h2>
{% endif %}

<hr class="border border-info bg-info">
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% if request.resolver_match.url_name == 'signup' %}
        <button class="w3-button w3-teal">회원가입</button>
    {% elif request.resolver_match.url_name == 'login' %}
        <button class="w3-button w3-teal">로그인</button>
        <a href="{% url 'accounts:signup' %}" class='w3-button btn-secondary text-decoration-none'>가입하기</a>
    {% elif request.resolver_match.url_name == 'update' %}
        <button class="w3-button w3-teal">수정</button>
        <a href="{% url 'accounts:delete' %}" class='w3-button btn-danger w3-hover-red text-decoration-none' data-toggle="modal" data-target="#UserDelete">회원탈퇴</a>
    {% else %}
        <button class="w3-button w3-teal">수정</button>
    {% endif %}
</form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
PROFILE
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block style %}
<style>
    .scrollmenu {
    overflow: auto;
    white-space: nowrap;
}
.card-body {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  width: 158px;
  height: 100px;
}
.movie_card{
    display:inline-block;
}
  /* .card-body, .movie_title{
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
} */
</style>
{% endblock %}
{% block context %}
<!-- 프로필 -->
<div class="container my-5 w3-border-bottom">
    <h3><i class="fas fa-user-circle align-self-center mx-3 py-3"></i>{{ user.username }}님의 프로필</h3>
    
    {% if request.user.is_superuser %}
    <p class="text-lg" style="font-size: large;">이름 : {{ user.first_name }} {{ user.last_name }}</p>
    <div class="d-flex justify-content-between">
        <p class="text-lg" style="font-size: large;">이메일 : {{ user.email }}</p>
        <div>
            <a href="/admin/" class="text-dark mr-3">관리자페이지</a>
            <a href="{% url 'accounts:update' %}" class="text-dark ">회원정보수정</a>
        </div>
    </div>  
    {% else %}
    <p class="text-lg" style="font-size: large;">이름 : {{ user.first_name }} {{ user.last_name }}</p>
    <div class="d-flex justify-content-between">
        <p class="text-lg" style="font-size: large;">이메일 : {{ user.email }}</p>
        <a href="{% url 'accounts:update' %}" class="text-dark ">회원정보수정</a>
    </div>
    {% endif %}
    
    
</div>

<div class="container mb-5">
    <h4 class="mb-4"><i class="fas">{{ user.username }}님이 좋아하는 영화 </i></h4>
    <hr>
    
        {% if movies %}
            <div class="container-fulid mx-0 px-0 scrollmenu" >
                {% for movie in movies %}
                <div class="card movie_card">
                    <!-- 영화 이미지 -->
                    <a href="{% url 'movies:detail' movie.pk %}">
                    <img src="https://image.tmdb.org/t/p/w154{{ movie.poster_path }}" alt="{{ movie.title }}" class="card-img-top" style="height:225px">
                        
                    </a>
                    <div class="card-body">
                        <!-- 영화 제목 -->
                        <a href="{% url 'movies:detail' movie.pk %}" class="text-dark text-decoration-none">{{ movie.title }}</a>
                        <hr>
                        <div class="container-fluid px-0">
                            <div class="d-flex justify-content-between">
                                <div class="flex-fill">
                                    <span><i class="fas fa-star" style="color:crimson">{{ movie.vote_average }}</i></span>
                                </div>
                                <div>
                                    {% if request.user in movie.liked_users.all %}
                                        {% if request.user.is_authenticated %}
                                            <i class="fas fa-heart like-button align-self-center" style="color:crimson" data-id="{{ movie.pk }}"></i>
                                        {% else %}
                                            <i class="fas fa-heart align-self-center" style="color:crimson" onclick="alert('로그인이 필요합니다.')"></i>
                                        {% endif %}
                                    {% else %}
                                        {% if request.user.is_authenticated %}
                                            <i class="fas fa-heart like-button align-self-center" style="color:black" data-id="{{ movie.pk }}"></i>
                                        {% else %}
                                            <i class="fas fa-heartalign-self-center" style="color:black" onclick="alert('로그인이 필요합니다.')"></i>
                                        {% endif %}
                                    {% endif %}
                                    <span id="like-count-{{ movie.pk }}">{{ movie.liked_users.all|length }}</span>
                                </div>
                            </div>
                        </div>
                  </div>
                </div>
                {% endfor %}
            </div>
        {% else %}  
            <p class="my-3 text-muted">아직 좋아하는 영화가 없어요 ㅠㅠ</p>
        {% endif %}
            


</div>


  
<div class="container mt-0 mb-5 p-1">
    <h4 class="mb-3"> 작성하신 게시글 </h4>
    <hr class="my-2">
    <div class="row" >
        <div class="col-1 text-center">분류</div>
        <div class="col-5 text-center">제목</div>
        <div class="col-2 text-center">스크랩</div>
        <div class="col-2 text-center">조회 수</div>
        <div class="col-2 text-center">작성일</div>
    </div>
    <hr class="my-2">
    <tbody>
        {% for article in user.article_set.all %}
            <div class="row">
                <div class="col-1 text-center">{{ article.board.name_short }}</div>
                <div class="col-5">
                    <a href="{% url 'community:detail' article.pk %}" class="text-dark">{{article.title}}</a>
                </div>
                <div class="col-2 text-center">{{ article.liked_users.all|length }}</div>
                <div class="col-2 text-center">{{ article.hits }}</div>
                <div class="col-2 text-center">
                    <!-- 오늘 날짜면 시간만 / 아니면 날짜 출력 -->
                    {% if article.created_at|date:"Y-m-d" == nowDate %}
                        {{ article.created_at | date:"H:i" }}
                    {% else %}
                        {{ article.created_at | date:"Y-m-d" }}
                    {% endif %}
                </div>
            </div>
            <hr class="my-2">
            
        {% endfor %}
    </tbody>
</div>


<div class="container mt-0 p-1">
    <h4 class="my-2"> 스크랩한 게시글 </h4>
    <hr class="my-2">
    <div class="row" >
        <div class="col-1 text-center">분류</div>
        <div class="col-5 text-center">제목</div>
        <div class="col-2 text-center">작성자</div>
        <div class="col-2 text-center">조회 수</div>
        <div class="col-2 text-center">작성일</div>
    </div>
    <hr class="my-2">
    <tbody>
        {% for article in user.liked_articles.all %}
            <div class="row">
                <div class="col-1 text-center">{{ article.board.name_short }}</div>
                <div class="col-5">
                    <a href="{% url 'community:detail' article.pk %}" class="text-dark">{{article.title}}</a>
                </div>
                <div class="col-2 text-center">{{ article.author }}</div>
                <div class="col-2 text-center">{{ article.hits }}</div>
                <div class="col-2 text-center">
                    <!-- 오늘 날짜면 시간만 / 아니면 날짜 출력 -->
                    {% if article.created_at|date:"Y-m-d" == nowDate %}
                        {{ article.created_at | date:"H:i" }}
                    {% else %}
                        {{ article.created_at | date:"Y-m-d" }}
                    {% endif %}
                </div>
            </div>
            <hr class="my-2">
            
        {% endfor %}
    </tbody>
</div>

{% endblock %}


{% block script %}
<script>

(function ($) {
  "use strict";
  // Auto-scroll
  $('#myCarousel').carousel({
    interval: 5000000000
  });

  // Control buttons
  $('.next').click(function () {
    $('.carousel').carousel('next');
    return false;
  });
  $('.prev').click(function () {
    $('.carousel').carousel('prev');
    return false;
  });

  // On carousel scroll
  $("#myCarousel").on("slide.bs.carousel", function (e) {
    var $e = $(e.relatedTarget);
    var idx = $e.index();
    var itemsPerSlide = 4;
    var totalItems = $(".carousel-item").length;
    if (idx >= totalItems - (itemsPerSlide - 1)) {
      var it = itemsPerSlide -
          (totalItems - idx);
      for (var i = 0; i < it; i++) {
        // append slides to end 
        if (e.direction == "left") {
          $(
            ".carousel-item").eq(i).appendTo(".carousel-inner");
        } else {
          $(".carousel-item").eq(0).appendTo(".carousel-inner");
        }
      }
    }
  });
})
(jQuery);

// 이미지 resize
$(document).ready(function(){
$('.ReSizeImage').each(function(){
    var width = 154
    var ratio = 1.5
    $(this).css("width", 154)
    $(this).css("height", width*ratio)

    })
})

// 좋아요
$('.like-button').on('click',function(event){
      const movieId = event.target.dataset.id
      if (movieId !== undefined) {
        axios.get(`/movies/${movieId}/like/`)

        .then((response) => {

          document.querySelector(`#like-count-${movieId}`).innerText = response.data.count

          if (response.data.movie_liked) {
            event.target.style.color = 'crimson'
          } else {
            event.target.style.color = 'black'
          }
        })
        .catch((error) => {
          console.log(error)
        })
      }
    })
</script>
{% endblock %}