accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
]

community/urls.py
from django.urls import path
from . import views


app_name = 'community'

urlpatterns = [
    path('', views.community, name='community'),
    path('create/', views.create_article, name='create_article_noboard'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    path('<int:article_pk>/comment/create/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/update/', views.update_comment, name='update_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:article_pk>/comment/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('<str:board_name>/', views.board, name='board'),
    path('<str:board_name>/create/', views.create_article, name='create_article'),
]

movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('', views.start),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.index, name='index'),
    path('search/<str:sort>/', views.search, name="search"),
    path('index/<str:sort>/', views.index, name='index_sort'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'),
    path('<int:movie_pk>/review/create/', views.review_create, name='review_create'),
    path('<int:movie_pk>/review/<int:review_pk>/like/', views.review_like, name='review_like'),
    path('<int:movie_pk>/review/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/review/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
]

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-teal.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% bootstrap_css %}

    {% block head %}
    {% endblock %}
</head>

{% block style %}
{% endblock %}

<style>
html, body {
margin: 0;
height: 100%;
}
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}


body{
  background-color: white;
}
#mySidebar{
  background-color: #1B2631;
}
#HEADER{
  background-color: white;
}
#Main_Context{
  background-color: white;
}
footer{
  background-color: white;
}


</style>
<body class="w3-content" style="max-width:1200px">
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block  w3-collapse w3-top" style="z-index:3;width:250px;" id="mySidebar">
  <div id="LOGO" class="w3-container w3-display-container w3-padding-16">
    <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
    <a href="{% url 'movies:main' %}" class="flex-fill ml-2">
        <img src="{% static 'image/logo_white.png' %}" alt="LOGO" style="width:200px; height:60px">
    </a>
  </div>
  <div class="w3-padding-32 w3-large w3-text-grey" style="font-weight:bold">
    
    
    {% if request.path == '/movies/' %}
      <a class="w3-bar-item w3-button" href="{% url 'movies:main' %}" style="color: white;">HOME</a>
    {% else %}
      <a class="w3-bar-item w3-button text-decoration-none" href="{% url 'movies:main' %}" style="color: rgb(145, 141, 141);">HOME</a>
    {% endif %}
    
    
    {% if request.resolver_match.app_name == 'movies' and request.path != '/movies/about/' and request.path != '/movies/' %}
    <a class="w3-bar-item w3-button text-decoration-none" href="{% url 'movies:index' %}" style="color: white;">MOVIES</a>
    {% else %}
    <a class="w3-bar-item w3-button text-decoration-none" href="{% url 'movies:index' %}" style="color: rgb(145, 141, 141);">MOVIES</a>
    {% endif %}
    {% if request.resolver_match.app_name == 'community' %}
    <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-left-align" id="myBtn" style="color: white;">
      COMMUNITY <i class="fa fa-caret-down"></i>
    </a>
    {% else %}
    <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-left-align text-decoration-none" id="myBtn" style="color: rgb(145, 141, 141);">
      COMMUNITY <i class="fa fa-caret-down"></i>
    </a>
    {% endif %}
    
    <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
        <a href="{% url 'community:board' 'notice' %}" class="w3-bar-item w3-button" style="color: white;">공지사항</a>
        <a href="{% url 'community:board' 'free' %}" class="w3-bar-item w3-button" style="color: white;">자유게시판</a>
        <a href="{% url 'community:board' 'recommend' %}" class="w3-bar-item w3-button" style="color: white;">추천게시판</a>
    </div>
  </div>
</nav>
<!-- Top menu on small screens -->
<header class="w3-bar w3-top w3-hide-large w3-light-grey w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">
    <a href="{% url 'movies:main' %}" class="flex-fill ml-2">
        <img src="{% static 'image/logo.png' %}" alt="LOGO" style="width:130px; height:35px">
    </a>
    </div>
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    <div class="w3-bar-item w3-right w3-padding-16">
      <div id="UserInfoTop" class="d-flex justify-content-center align-items-center my-auto">
        {% if request.user.is_authenticated %}
            <div>
              <a href="{% url 'accounts:profile' %}" class="w3-bar-item w3-button text-muted" style="padding:0;">
                  <i class="fas fa-user-circle"></i> {{ request.user.username }}
              </a>
            </div>
            <div>
              <form action="{% url 'accounts:logout' %}" method="POST" style="display:inline">
                  {% csrf_token %}
                  <button class="w3-bar-item w3-button text-decoration-none">
                      <small class="text-muted">LOGOUT</small>
                  </button>
              </form>
            </div>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="w3-bar-item w3-button text-dark text-decoration-none"><small>LOGIN</small></a>
            <a href="{% url 'accounts:signup' %}" class="w3-bar-item w3-button text-dark text-decoration-none"><small>SIGNUP</small></a>
        {% endif %} 
    </div>
    </div>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:130px"></div>
  
  <!-- Top header -->
  <header class="w3-container w3-xlarge d-none d-lg-block" id="HEADER" style="margin-top: 0;">
    <div id="UserInfo" class="w3-right">
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}" class="w3-bar-item w3-button text-muted" style="padding:0;">
                <i class="fas fa-user-circle"></i> {{ request.user.username }}
            </a>
            <form action="{% url 'accounts:logout' %}" method="POST" style="display:inline">
                {% csrf_token %}
                <button class="w3-bar-item w3-button text-decoration-none">
                    <small class="text-muted">LOGOUT</small>
                </button>
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="w3-bar-item w3-button text-dark text-decoration-none"><small>LOGIN</small></a>
            <a href="{% url 'accounts:signup' %}" class="w3-bar-item w3-button text-dark text-decoration-none"><small>SIGNUP</small></a>
        {% endif %} 
    </div>
  </header>

  <!--context -->
  <!-- alert -->
    {% if messages %}
    {% for message in messages %}
        <div class="row" style="margin:20px auto;">
        <div class="col-sm-12">
            <div class="alert alert-{{ message.tags }}">
            {{ message.message }}
            </div>
        </div>
        </div>
    {% endfor %}
    {% endif %}
  <div class="w3-display-container w3-container" id="Main_Context">
      {% block context %}
      {% endblock %}
  </div>
  <!-- Footer -->
  <footer class="container w3-padding-64 w3-small w3-center" id="footer" style="bottom:0">
    <a href="{% url 'movies:main' %}" class="ml-2">
        <img src="{% static 'image/logo.png' %}" alt="LOGO" style="width:200px; height:60px" class="mb-4"> 
    </a>
    <p>MADE BY JONGWOO LEE, JIYOUNG KIM</p>
    <p>POWERED BY w3schools.com</p>
  </footer>
<!-- End page content -->
</div>


</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% bootstrap_javascript jquery='full' %}

<script>
// Accordion 
function myAccFunc() {
  var x = document.getElementById("demoAcc");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// context margin 설정
$(document).ready(function() {
    const WindowHeight = $(window).height()
    const LogoHeight = $("#LOGO").outerHeight()
    const UserInfoHeight = $("#UserInfo").outerHeight()
    const FooterHeight = $('footer').outerHeight()
    const ContextHeight = $('#Main_Context').outerHeight()

    $("#HEADER").css("height", LogoHeight)
    $("#UserInfo").css("margin-top", (LogoHeight/2)-(UserInfoHeight/2))
    $('#Main_Context').css("padding-bottom", WindowHeight-LogoHeight-ContextHeight-FooterHeight+300)

})

</script>
{% block script %}
{% endblock %}



</body>
</html>